import type {
  Card,
  CardSet,
  GradePop,
  GradingCompany,
  Listing,
  PricePoint,
  Sale,
  Seller,
} from "./types";

function seedHash(seed: string) {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function rand(seed: number) {
  const x = Math.sin(seed) * 10000;
  return x - Math.floor(x);
}

function history(base: number, seed: string, weeks = 52): PricePoint[] {
  const s = seedHash(seed);
  const points: PricePoint[] = [];
  let price = base * (0.62 + rand(s) * 0.12);
  for (let i = weeks; i >= 0; i--) {
    const t = (weeks - i) / weeks;
    const wave = Math.sin(s / 1000 + i / 7) * 0.055;
    const noise = (rand(s + i * 17) - 0.5) * 0.045;
    const drift = t * 0.28;
    price = base * (0.7 + drift + wave + noise);
    const d = new Date("2026-08-17T00:00:00Z");
    d.setDate(d.getDate() - i * 7);
    points.push({
      date: d.toISOString().slice(0, 10),
      price: Math.max(8, Math.round(price)),
    });
  }
  points[points.length - 1].price = base;
  return points;
}

function sales(
  base: number,
  seed: string,
  count = 8,
): Sale[] {
  const s = seedHash(seed);
  const sources = ["PWCC", "Goldin", "eBay", "Heritage", "Private", "RareCandy"];
  const grades = [
    { condition: "Near Mint", grade: undefined, company: undefined, mult: 1 },
    { condition: "Mint", grade: "10", company: "PSA" as GradingCompany, mult: 2.4 },
    { condition: "Mint", grade: "9", company: "PSA" as GradingCompany, mult: 1.35 },
    { condition: "Mint", grade: "9.5", company: "BGS" as GradingCompany, mult: 1.7 },
    { condition: "Mint", grade: "10", company: "CGC" as GradingCompany, mult: 1.9 },
    { condition: "Lightly Played", grade: undefined, company: undefined, mult: 0.72 },
    { condition: "Mint", grade: "8", company: "PSA" as GradingCompany, mult: 0.95 },
    { condition: "Near Mint", grade: "9.5", company: "CGC" as GradingCompany, mult: 1.45 },
  ];
  return Array.from({ length: count }, (_, i) => {
    const g = grades[(s + i * 3) % grades.length];
    const d = new Date("2026-08-16T00:00:00Z");
    d.setDate(d.getDate() - (i * 6 + ((s + i) % 5)));
    const jitter = 0.92 + rand(s + i * 31) * 0.16;
    return {
      id: `${seed}-sale-${i}`,
      date: d.toISOString().slice(0, 10),
      price: Math.max(12, Math.round(base * g.mult * jitter)),
      condition: g.condition,
      grade: g.grade,
      company: g.company,
      source: sources[(s + i) % sources.length],
    };
  });
}

function pops(seed: string, scale: number): GradePop[] {
  const s = seedHash(seed);
  const psa10 = Math.max(4, Math.round(scale * (0.04 + rand(s) * 0.08)));
  const psa9 = Math.max(18, Math.round(scale * (0.22 + rand(s + 1) * 0.12)));
  const psa8 = Math.max(30, Math.round(scale * (0.28 + rand(s + 2) * 0.1)));
  const bgs95 = Math.max(6, Math.round(scale * (0.05 + rand(s + 3) * 0.05)));
  const bgs10 = Math.max(1, Math.round(scale * (0.008 + rand(s + 4) * 0.012)));
  const cgc10 = Math.max(3, Math.round(scale * (0.03 + rand(s + 5) * 0.04)));
  const cgc95 = Math.max(10, Math.round(scale * (0.08 + rand(s + 6) * 0.06)));
  return [
    { company: "PSA", grade: "10", population: psa10 },
    { company: "PSA", grade: "9", population: psa9 },
    { company: "PSA", grade: "8", population: psa8 },
    { company: "BGS", grade: "10", population: bgs10 },
    { company: "BGS", grade: "9.5", population: bgs95 },
    { company: "CGC", grade: "10", population: cgc10 },
    { company: "CGC", grade: "9.5", population: cgc95 },
  ];
}

function listingsFor(
  seed: string,
  base: number,
  sellerIds: string[],
): Listing[] {
  const s = seedHash(seed);
  const variants: Array<Omit<Listing, "id" | "sellerId">> = [
    { price: Math.round(base * 0.92), condition: "Near Mint", shipping: 12, quantity: 1 },
    {
      price: Math.round(base * 2.35),
      condition: "Mint",
      grade: "10",
      company: "PSA",
      certNumber: String(8_400_000 + (s % 500_000)),
      shipping: 18,
      quantity: 1,
    },
    {
      price: Math.round(base * 1.28),
      condition: "Mint",
      grade: "9",
      company: "PSA",
      certNumber: String(7_200_000 + (s % 400_000)),
      shipping: 16,
      quantity: 1,
    },
    {
      price: Math.round(base * 0.7),
      condition: "Lightly Played",
      shipping: 9,
      quantity: 2,
    },
    {
      price: Math.round(base * 1.62),
      condition: "Mint",
      grade: "9.5",
      company: "BGS",
      certNumber: String(1_100_000 + (s % 200_000)),
      shipping: 20,
      quantity: 1,
    },
    {
      price: Math.round(base * 1.48),
      condition: "Mint",
      grade: "10",
      company: "CGC",
      certNumber: String(4_500_000 + (s % 300_000)),
      shipping: 15,
      quantity: 1,
    },
  ];
  return variants.slice(0, 4 + (s % 3)).map((v, i) => ({
    ...v,
    id: `${seed}-list-${i}`,
    sellerId: sellerIds[(s + i) % sellerIds.length],
  }));
}

export const sellers: Seller[] = [
  {
    id: "s1",
    slug: "vault-and-foil",
    name: "Vault & Foil",
    city: "Chicago",
    rating: 4.97,
    sales: 12840,
    joined: "2018",
    response: "under 2 hours",
    verified: true,
  },
  {
    id: "s2",
    slug: "kanto-reserve",
    name: "Kanto Reserve",
    city: "Tokyo",
    rating: 5,
    sales: 3412,
    joined: "2020",
    response: "same day",
    verified: true,
  },
  {
    id: "s3",
    slug: "cerulean-slab",
    name: "Cerulean Slab Co.",
    city: "Austin",
    rating: 4.84,
    sales: 7690,
    joined: "2019",
    response: "under 4 hours",
    verified: true,
  },
  {
    id: "s4",
    slug: "indigo-plateau",
    name: "Indigo Plateau",
    city: "New York",
    rating: 4.91,
    sales: 21004,
    joined: "2016",
    response: "under 1 hour",
    verified: true,
  },
  {
    id: "s5",
    slug: "gold-berry",
    name: "Gold Berry Collectibles",
    city: "Los Angeles",
    rating: 4.73,
    sales: 5521,
    joined: "2021",
    response: "next day",
    verified: true,
  },
  {
    id: "s6",
    slug: "oaks-lab",
    name: "Oak's Laboratory",
    city: "Pallet",
    rating: 5,
    sales: 980,
    joined: "2022",
    response: "same day",
    verified: true,
  },
  {
    id: "s7",
    slug: "rocket-exchange",
    name: "Rocket Exchange",
    city: "Las Vegas",
    rating: 4.61,
    sales: 18902,
    joined: "2017",
    response: "under 6 hours",
    verified: false,
  },
];

const S = sellers.map((s) => s.id);

export const sets: CardSet[] = [
  {
    id: "base",
    slug: "base-set",
    name: "Base Set",
    series: "Original",
    year: 1999,
    released: "1999-01-09",
    printed: 102,
    language: "English",
    blurb: "The set that built the hobby. Shadowless holos still set the ceiling.",
  },
  {
    id: "jungle",
    slug: "jungle",
    name: "Jungle",
    series: "Original",
    year: 1999,
    released: "1999-06-16",
    printed: 64,
    language: "English",
    blurb: "The first expansion. Flareon, Vileplume, and a quieter kind of grail.",
  },
  {
    id: "fossil",
    slug: "fossil",
    name: "Fossil",
    series: "Original",
    year: 1999,
    released: "1999-10-10",
    printed: 62,
    language: "English",
    blurb: "Dragonite, Aerodactyl, and the last true Wizards-era fossils.",
  },
  {
    id: "rocket",
    slug: "team-rocket",
    name: "Team Rocket",
    series: "Original",
    year: 2000,
    released: "2000-04-24",
    printed: 83,
    language: "English",
    blurb: "Dark Pokémon, darker corners. The first set with a real villain.",
  },
  {
    id: "neo-gen",
    slug: "neo-genesis",
    name: "Neo Genesis",
    series: "Neo",
    year: 2000,
    released: "2000-12-16",
    printed: 111,
    language: "English",
    blurb: "Johto arrives. Lugia on the booster was a warning shot.",
  },
  {
    id: "neo-dis",
    slug: "neo-discovery",
    name: "Neo Discovery",
    series: "Neo",
    year: 2001,
    released: "2001-06-01",
    printed: 75,
    language: "English",
    blurb: "Umbreon, Espeon, and the first time Eeveelutions felt like art.",
  },
  {
    id: "skyridge",
    slug: "skyridge",
    name: "Skyridge",
    series: "e-Card",
    year: 2003,
    released: "2003-05-12",
    printed: 182,
    language: "English",
    blurb: "Crystal cards. The last Wizards English set, and still the hardest pull.",
  },
  {
    id: "cele",
    slug: "celebrations",
    name: "Celebrations",
    series: "Sword & Shield",
    year: 2021,
    released: "2021-10-08",
    printed: 25,
    language: "English",
    blurb: "Twenty-five years, reprinted as relics. Classic holos in modern sleeves.",
  },
  {
    id: "hf",
    slug: "hidden-fates",
    name: "Hidden Fates",
    series: "Sun & Moon",
    year: 2019,
    released: "2019-08-23",
    printed: 69,
    language: "English",
    blurb: "Shiny Vault. Charizard GX still moves rooms when it hits the table.",
  },
  {
    id: "es",
    slug: "evolving-skies",
    name: "Evolving Skies",
    series: "Sword & Shield",
    year: 2021,
    released: "2021-08-27",
    printed: 203,
    language: "English",
    blurb: "The modern grail set. Umbreon VMAX alt art rewired the market.",
  },
  {
    id: "sf",
    slug: "shining-fates",
    name: "Shining Fates",
    series: "Sword & Shield",
    year: 2021,
    released: "2021-03-19",
    printed: 73,
    language: "English",
    blurb: "Baby Shinies and a Charizard VMAX that still prints money.",
  },
  {
    id: "bs",
    slug: "brilliant-stars",
    name: "Brilliant Stars",
    series: "Sword & Shield",
    year: 2022,
    released: "2022-02-25",
    printed: 172,
    language: "English",
    blurb: "Charizard VSTAR and the Trainer Gallery that collectors actually chase.",
  },
  {
    id: "pe",
    slug: "paldea-evolved",
    name: "Paldea Evolved",
    series: "Scarlet & Violet",
    year: 2023,
    released: "2023-06-09",
    printed: 193,
    language: "English",
    blurb: "Iono, Magikarp, and the first Paldean illustration rares that stuck.",
  },
  {
    id: "tm",
    slug: "twilight-masquerade",
    name: "Twilight Masquerade",
    series: "Scarlet & Violet",
    year: 2024,
    released: "2024-05-24",
    printed: 167,
    language: "English",
    blurb: "Ogerpon, Greninja, and a blood-moon palette that photographs well.",
  },
  {
    id: "prism",
    slug: "prismatic-evolutions",
    name: "Prismatic Evolutions",
    series: "Scarlet & Violet",
    year: 2025,
    released: "2025-01-17",
    printed: 131,
    language: "English",
    blurb: "Eeveelution special arts. The newest chase set still finding its floor.",
  },
  {
    id: "promo",
    slug: "wizards-promos",
    name: "Wizards Black Star Promos",
    series: "Promo",
    year: 1999,
    released: "1999-07-01",
    printed: 53,
    language: "English",
    blurb: "Movie packs, cereal boxes, and the Pikachu that started arguments.",
  },
];

type Draft = Omit<Card, "priceHistory" | "recentSales" | "listings" | "populations"> & {
  popScale: number;
};

const drafts: Draft[] = [
  {
    id: "c1",
    slug: "base-set-charizard-4",
    name: "Charizard",
    pokemon: "Charizard",
    pokedex: 6,
    setId: "base",
    number: "4/102",
    rarity: "Rare Holo",
    type: "Fire",
    hp: 120,
    illustrator: "Mitsuhiro Arita",
    year: 1999,
    releaseDate: "1999-01-09",
    description:
      "The English holofoil that still defines the hobby. Unlimited copies trade daily; first-edition and shadowless sit in a different atmosphere entirely.",
    flavor: "Spits fire that is hot enough to melt boulders.",
    marketPrice: 4280,
    change7d: 3.4,
    change30d: 11.2,
    weeklyVolume: 41,
    featured: true,
    trending: true,
    tags: ["vintage", "holo", "icon", "arita"],
    popScale: 4200,
  },
  {
    id: "c2",
    slug: "base-set-pikachu-58",
    name: "Pikachu",
    pokemon: "Pikachu",
    pokedex: 25,
    setId: "base",
    number: "58/102",
    rarity: "Common",
    type: "Lightning",
    hp: 40,
    illustrator: "Mitsuhiro Arita",
    year: 1999,
    releaseDate: "1999-01-09",
    description:
      "The yellow common that outlived every chase around it. High-grade copies are deceptively thin — most were played, sleeved late, or bent in a binder.",
    flavor: "When several of these Pokémon gather, their electricity can cause lightning storms.",
    marketPrice: 64,
    change7d: -1.2,
    change30d: 4.8,
    weeklyVolume: 188,
    featured: true,
    tags: ["vintage", "mascot", "arita"],
    popScale: 18000,
  },
  {
    id: "c3",
    slug: "base-set-mewtwo-10",
    name: "Mewtwo",
    pokemon: "Mewtwo",
    pokedex: 150,
    setId: "base",
    number: "10/102",
    rarity: "Rare Holo",
    type: "Psychic",
    hp: 60,
    illustrator: "Ken Sugimori",
    year: 1999,
    releaseDate: "1999-01-09",
    description:
      "Sugimori’s laboratory stare. Less theatrical than Charizard, more severe — and still one of the cleanest holos Wizards ever printed.",
    flavor: "It was created by a scientist after years of horrific gene-splicing experiments.",
    marketPrice: 312,
    change7d: 1.8,
    change30d: 6.4,
    weeklyVolume: 67,
    featured: true,
    trending: true,
    tags: ["vintage", "holo", "legendary"],
    popScale: 6100,
  },
  {
    id: "c4",
    slug: "neo-genesis-lugia-9",
    name: "Lugia",
    pokemon: "Lugia",
    pokedex: 249,
    setId: "neo-gen",
    number: "9/111",
    rarity: "Rare Holo",
    type: "Colorless",
    hp: 90,
    illustrator: "Kazuma Koda",
    year: 2000,
    releaseDate: "2000-12-16",
    description:
      "The guardian of the seas, printed just as the hobby thinned out. First-edition copies remain one of the most complete Neo-era trophies.",
    flavor: "It is said to be the guardian of the seas. It is rumored to have been seen on the night of a storm.",
    marketPrice: 890,
    change7d: 5.1,
    change30d: 14.6,
    weeklyVolume: 22,
    featured: true,
    trending: true,
    tags: ["neo", "holo", "legendary"],
    popScale: 2100,
  },
  {
    id: "c5",
    slug: "neo-discovery-umbreon-13",
    name: "Umbreon",
    pokemon: "Umbreon",
    pokedex: 197,
    setId: "neo-dis",
    number: "13/75",
    rarity: "Rare Holo",
    type: "Darkness",
    hp: 80,
    illustrator: "Atsuko Nishida",
    year: 2001,
    releaseDate: "2001-06-01",
    description:
      "The original English Umbreon holo. Rings like a night-light, and still the card modern alt arts are measured against.",
    flavor: "When agitated, this Pokémon protects itself by spraying poisonous sweat from its pores.",
    marketPrice: 540,
    change7d: 2.2,
    change30d: 9.1,
    weeklyVolume: 29,
    featured: true,
    trending: true,
    tags: ["neo", "eeveelution", "holo"],
    popScale: 2400,
  },
  {
    id: "c6",
    slug: "evolving-skies-umbreon-vmax-215",
    name: "Umbreon VMAX",
    pokemon: "Umbreon",
    pokedex: 197,
    setId: "es",
    number: "215/203",
    rarity: "Special Illustration Rare",
    type: "Darkness",
    hp: 310,
    illustrator: "Teeziro",
    year: 2021,
    releaseDate: "2021-08-27",
    description:
      "The moonlit alt art that reset modern pricing. Raw copies still clear four figures; PSA 10s behave like blue-chip stock.",
    flavor: "Moonlight has given this Pokémon a new silhouette — and a new ceiling.",
    marketPrice: 1240,
    change7d: -2.4,
    change30d: 7.8,
    weeklyVolume: 54,
    featured: true,
    trending: true,
    tags: ["modern", "alt art", "eeveelution", "sir"],
    popScale: 8600,
  },
  {
    id: "c7",
    slug: "hidden-fates-charizard-gx-sv49",
    name: "Charizard GX",
    pokemon: "Charizard",
    pokedex: 6,
    setId: "hf",
    number: "SV49/SV94",
    rarity: "Secret Rare",
    type: "Fire",
    hp: 250,
    illustrator: "aky CG Works",
    year: 2019,
    releaseDate: "2019-08-23",
    description:
      "Shiny Vault Charizard. Rainbow foil, black body, the card that taught a new generation what a chase feels like.",
    marketPrice: 368,
    change7d: 4.6,
    change30d: 12.9,
    weeklyVolume: 73,
    trending: true,
    tags: ["shiny", "secret", "charizard"],
    popScale: 9200,
  },
  {
    id: "c8",
    slug: "skyridge-crystal-charizard-146",
    name: "Charizard",
    pokemon: "Charizard",
    pokedex: 6,
    setId: "skyridge",
    number: "146/144",
    rarity: "Secret Rare",
    type: "Fire",
    hp: 100,
    illustrator: "Kouki Saitou",
    year: 2003,
    releaseDate: "2003-05-12",
    description:
      "Crystal Charizard. Transparent holofoil on e-Reader stock — one of the scarcest English print runs of the Wizards era.",
    flavor: "A crystal body that barely survived the printer.",
    marketPrice: 11800,
    change7d: 1.1,
    change30d: 8.4,
    weeklyVolume: 3,
    featured: true,
    tags: ["crystal", "skyridge", "grail"],
    popScale: 420,
  },
  {
    id: "c9",
    slug: "celebrations-charizard-4",
    name: "Charizard",
    pokemon: "Charizard",
    pokedex: 6,
    setId: "cele",
    number: "4/102",
    rarity: "Rare Holo",
    type: "Fire",
    hp: 120,
    illustrator: "Mitsuhiro Arita",
    year: 2021,
    releaseDate: "2021-10-08",
    description:
      "The 25th-anniversary reprint of Arita’s original. Same stare, modern stock, a gateway that still holds a premium over bulk holos.",
    marketPrice: 52,
    change7d: 0.8,
    change30d: -2.1,
    weeklyVolume: 210,
    isNew: false,
    tags: ["reprint", "holo", "arita"],
    popScale: 24000,
  },
  {
    id: "c10",
    slug: "shining-fates-charizard-vmax-074",
    name: "Charizard VMAX",
    pokemon: "Charizard",
    pokedex: 6,
    setId: "sf",
    number: "074/072",
    rarity: "Secret Rare",
    type: "Fire",
    hp: 330,
    illustrator: "aky CG Works",
    year: 2021,
    releaseDate: "2021-03-19",
    description:
      "Rainbow Shiny Charizard VMAX. Thick texture, loud foil, still the centerpiece of most Shining Fates collections.",
    marketPrice: 214,
    change7d: 6.2,
    change30d: 15.4,
    weeklyVolume: 96,
    trending: true,
    tags: ["shiny", "vmax", "secret"],
    popScale: 14000,
  },
  {
    id: "c11",
    slug: "brilliant-stars-charizard-vstar-174",
    name: "Charizard VSTAR",
    pokemon: "Charizard",
    pokedex: 6,
    setId: "bs",
    number: "174/172",
    rarity: "Secret Rare",
    type: "Fire",
    hp: 280,
    illustrator: "5ban Graphics",
    year: 2022,
    releaseDate: "2022-02-25",
    description:
      "Gold Charizard VSTAR. Less narrative than the alt arts, more object — a bar of foil that still clears a week of rent.",
    marketPrice: 78,
    change7d: -0.6,
    change30d: 3.3,
    weeklyVolume: 134,
    tags: ["gold", "vstar", "secret"],
    popScale: 11000,
  },
  {
    id: "c12",
    slug: "team-rocket-dark-charizard-4",
    name: "Dark Charizard",
    pokemon: "Charizard",
    pokedex: 6,
    setId: "rocket",
    number: "4/82",
    rarity: "Rare Holo",
    type: "Fire",
    hp: 80,
    illustrator: "Ken Sugimori",
    year: 2000,
    releaseDate: "2000-04-24",
    description:
      "Charizard in a Rocket collar. First-edition holos are meaner and scarcer than their Base Set cousins of the same grade.",
    flavor: "A Charizard that has been trained by Team Rocket.",
    marketPrice: 620,
    change7d: 3.9,
    change30d: 10.5,
    weeklyVolume: 18,
    trending: true,
    tags: ["rocket", "dark", "holo"],
    popScale: 1900,
  },
  {
    id: "c13",
    slug: "jungle-flareon-3",
    name: "Flareon",
    pokemon: "Flareon",
    pokedex: 136,
    setId: "jungle",
    number: "3/64",
    rarity: "Rare Holo",
    type: "Fire",
    hp: 70,
    illustrator: "Kagemaru Himeno",
    year: 1999,
    releaseDate: "1999-06-16",
    description:
      "Himeno’s Jungle Flareon. Soft edges, hard demand — the Eeveelution vintage collectors actually finish sets for.",
    marketPrice: 188,
    change7d: 2.0,
    change30d: 5.7,
    weeklyVolume: 33,
    tags: ["jungle", "eeveelution", "holo"],
    popScale: 3800,
  },
  {
    id: "c14",
    slug: "fossil-dragonite-4",
    name: "Dragonite",
    pokemon: "Dragonite",
    pokedex: 149,
    setId: "fossil",
    number: "4/62",
    rarity: "Rare Holo",
    type: "Colorless",
    hp: 100,
    illustrator: "Kimiya Masago",
    year: 1999,
    releaseDate: "1999-10-10",
    description:
      "Masago’s sky-bound Dragonite. A Fossil staple that still surprises in PSA 10 — centering on this sheet was unkind.",
    marketPrice: 246,
    change7d: 1.4,
    change30d: 4.2,
    weeklyVolume: 27,
    tags: ["fossil", "dragon", "holo"],
    popScale: 2900,
  },
  {
    id: "c15",
    slug: "promo-pikachu-4",
    name: "Pikachu",
    pokemon: "Pikachu",
    pokedex: 25,
    setId: "promo",
    number: "4",
    rarity: "Promo",
    type: "Lightning",
    hp: 50,
    illustrator: "Ken Sugimori",
    year: 1999,
    releaseDate: "1999-11-10",
    description:
      "The original movie promo. Red cheeks, no set symbol drama — just the card a generation taped to the fridge.",
    marketPrice: 96,
    change7d: 0.4,
    change30d: 2.8,
    weeklyVolume: 58,
    tags: ["promo", "movie", "pikachu"],
    popScale: 7200,
  },
  {
    id: "c16",
    slug: "evolving-skies-rayquaza-v-194",
    name: "Rayquaza V",
    pokemon: "Rayquaza",
    pokedex: 384,
    setId: "es",
    number: "194/203",
    rarity: "Special Illustration Rare",
    type: "Dragon",
    hp: 210,
    illustrator: "5ban Graphics",
    year: 2021,
    releaseDate: "2021-08-27",
    description:
      "Alt-art Rayquaza tearing through cloud. The sibling chase to Umbreon in Evolving Skies, with a slightly more generous pull rate.",
    marketPrice: 286,
    change7d: -1.8,
    change30d: 5.6,
    weeklyVolume: 48,
    trending: true,
    tags: ["alt art", "dragon", "sir"],
    popScale: 7800,
  },
  {
    id: "c17",
    slug: "evolving-skies-sylveon-vmax-212",
    name: "Sylveon VMAX",
    pokemon: "Sylveon",
    pokedex: 700,
    setId: "es",
    number: "212/203",
    rarity: "Special Illustration Rare",
    type: "Psychic",
    hp: 310,
    illustrator: "Ryota Murayama",
    year: 2021,
    releaseDate: "2021-08-27",
    description:
      "Ribboned, pastel, and quietly expensive. The softest card in Evolving Skies and one of the hardest to keep centered.",
    marketPrice: 198,
    change7d: 3.1,
    change30d: 8.9,
    weeklyVolume: 37,
    tags: ["alt art", "eeveelution", "sir"],
    popScale: 6400,
  },
  {
    id: "c18",
    slug: "prismatic-umbreon-ex-161",
    name: "Umbreon ex",
    pokemon: "Umbreon",
    pokedex: 197,
    setId: "prism",
    number: "161/131",
    rarity: "Special Illustration Rare",
    type: "Darkness",
    hp: 280,
    illustrator: "DOM",
    year: 2025,
    releaseDate: "2025-01-17",
    description:
      "The newest moonlit Umbreon. Prismatic Evolutions special art — still discovering its long-term floor after a loud launch.",
    marketPrice: 412,
    change7d: -6.8,
    change30d: -14.2,
    weeklyVolume: 121,
    isNew: true,
    trending: true,
    tags: ["prismatic", "eeveelution", "sir", "new"],
    popScale: 3100,
  },
  {
    id: "c19",
    slug: "prismatic-espeon-ex-156",
    name: "Espeon ex",
    pokemon: "Espeon",
    pokedex: 196,
    setId: "prism",
    number: "156/131",
    rarity: "Special Illustration Rare",
    type: "Psychic",
    hp: 270,
    illustrator: "DOM",
    year: 2025,
    releaseDate: "2025-01-17",
    description:
      "Sunlit counterpart to the Umbreon SIR. Cleaner supply than the moon card, and a more patient bid book.",
    marketPrice: 168,
    change7d: -3.2,
    change30d: -8.4,
    weeklyVolume: 84,
    isNew: true,
    tags: ["prismatic", "eeveelution", "sir", "new"],
    popScale: 2800,
  },
  {
    id: "c20",
    slug: "twilight-greninja-ex-240",
    name: "Greninja ex",
    pokemon: "Greninja",
    pokedex: 658,
    setId: "tm",
    number: "240/167",
    rarity: "Special Illustration Rare",
    type: "Water",
    hp: 270,
    illustrator: "akio",
    year: 2024,
    releaseDate: "2024-05-24",
    description:
      "Water-shadow Greninja from Twilight Masquerade. A modern ninja card that photographs like a film still.",
    marketPrice: 142,
    change7d: 8.4,
    change30d: 19.6,
    weeklyVolume: 62,
    isNew: true,
    trending: true,
    tags: ["twilight", "sir", "water"],
    popScale: 4500,
  },
  {
    id: "c21",
    slug: "paldea-magikarp-203",
    name: "Magikarp",
    pokemon: "Magikarp",
    pokedex: 129,
    setId: "pe",
    number: "203/193",
    rarity: "Illustration Rare",
    type: "Water",
    hp: 30,
    illustrator: "Shigenori Negishi",
    year: 2023,
    releaseDate: "2023-06-09",
    description:
      "A pond full of Magikarp, painted like a joke that became a grail. The illustration rare that outran its own punchline.",
    marketPrice: 96,
    change7d: 1.6,
    change30d: 6.2,
    weeklyVolume: 77,
    tags: ["illustration", "paldea", "splash"],
    popScale: 9800,
  },
  {
    id: "c22",
    slug: "base-set-blastoise-2",
    name: "Blastoise",
    pokemon: "Blastoise",
    pokedex: 9,
    setId: "base",
    number: "2/102",
    rarity: "Rare Holo",
    type: "Water",
    hp: 100,
    illustrator: "Ken Sugimori",
    year: 1999,
    releaseDate: "1999-01-09",
    description:
      "The third starter holo. Always priced in Charizard’s shadow, which is exactly why complete-set buyers still pay up for nines.",
    marketPrice: 420,
    change7d: 2.7,
    change30d: 7.1,
    weeklyVolume: 24,
    tags: ["vintage", "starter", "holo"],
    popScale: 3600,
  },
  {
    id: "c23",
    slug: "base-set-venusaur-15",
    name: "Venusaur",
    pokemon: "Venusaur",
    pokedex: 3,
    setId: "base",
    number: "15/102",
    rarity: "Rare Holo",
    type: "Grass",
    hp: 100,
    illustrator: "Mitsuhiro Arita",
    year: 1999,
    releaseDate: "1999-01-09",
    description:
      "Arita’s garden tank. Unlimited holos are available; true gem mint copies are not. The green that finishes a Base Set page.",
    marketPrice: 268,
    change7d: 0.9,
    change30d: 3.8,
    weeklyVolume: 19,
    tags: ["vintage", "starter", "holo"],
    popScale: 3400,
  },
  {
    id: "c24",
    slug: "base-set-alakazam-1",
    name: "Alakazam",
    pokemon: "Alakazam",
    pokedex: 65,
    setId: "base",
    number: "1/102",
    rarity: "Rare Holo",
    type: "Psychic",
    hp: 80,
    illustrator: "Ken Sugimori",
    year: 1999,
    releaseDate: "1999-01-09",
    description:
      "Card number one. Spoons crossed, IQ advertised, still the cleanest opening to an English master set.",
    marketPrice: 198,
    change7d: 1.3,
    change30d: 4.4,
    weeklyVolume: 21,
    tags: ["vintage", "holo", "psychic"],
    popScale: 4000,
  },
  {
    id: "c25",
    slug: "jungle-jolteon-4",
    name: "Jolteon",
    pokemon: "Jolteon",
    pokedex: 135,
    setId: "jungle",
    number: "4/64",
    rarity: "Rare Holo",
    type: "Lightning",
    hp: 70,
    illustrator: "Kagemaru Himeno",
    year: 1999,
    releaseDate: "1999-06-16",
    description:
      "Static Himeno Jolteon. The sharpest of the Jungle Eeveelutions and the one most often off-center on the right.",
    marketPrice: 164,
    change7d: -0.4,
    change30d: 2.9,
    weeklyVolume: 26,
    tags: ["jungle", "eeveelution", "holo"],
    popScale: 3500,
  },
  {
    id: "c26",
    slug: "jungle-vaporeon-12",
    name: "Vaporeon",
    pokemon: "Vaporeon",
    pokedex: 134,
    setId: "jungle",
    number: "12/64",
    rarity: "Rare Holo",
    type: "Water",
    hp: 80,
    illustrator: "Kagemaru Himeno",
    year: 1999,
    releaseDate: "1999-06-16",
    description:
      "The aquatic Jungle holo. Quieter money than Flareon, cleaner art than most water cards of the era.",
    marketPrice: 154,
    change7d: 0.6,
    change30d: 3.1,
    weeklyVolume: 23,
    tags: ["jungle", "eeveelution", "holo"],
    popScale: 3300,
  },
  {
    id: "c27",
    slug: "fossil-aerodactyl-1",
    name: "Aerodactyl",
    pokemon: "Aerodactyl",
    pokedex: 142,
    setId: "fossil",
    number: "1/62",
    rarity: "Rare Holo",
    type: "Fighting",
    hp: 60,
    illustrator: "Koga Kazuo",
    year: 1999,
    releaseDate: "1999-10-10",
    description:
      "Fossil number one. A prehistoric holo that still looks like it was printed on a different press than the rest of the set.",
    marketPrice: 132,
    change7d: 2.4,
    change30d: 6.8,
    weeklyVolume: 17,
    tags: ["fossil", "holo"],
    popScale: 2700,
  },
  {
    id: "c28",
    slug: "neo-genesis-ho-oh-7",
    name: "Ho-Oh",
    pokemon: "Ho-Oh",
    pokedex: 250,
    setId: "neo-gen",
    number: "7/111",
    rarity: "Rare Holo",
    type: "Fire",
    hp: 110,
    illustrator: "Kimiya Masago",
    year: 2000,
    releaseDate: "2000-12-16",
    description:
      "Rainbow-winged counterpart to Lugia. First-edition copies remain thinner than the market pretends.",
    marketPrice: 410,
    change7d: 4.2,
    change30d: 9.8,
    weeklyVolume: 14,
    tags: ["neo", "legendary", "holo"],
    popScale: 1600,
  },
  {
    id: "c29",
    slug: "neo-discovery-espeon-1",
    name: "Espeon",
    pokemon: "Espeon",
    pokedex: 196,
    setId: "neo-dis",
    number: "1/75",
    rarity: "Rare Holo",
    type: "Psychic",
    hp: 80,
    illustrator: "Atsuko Nishida",
    year: 2001,
    releaseDate: "2001-06-01",
    description:
      "Nishida’s sunlit Espeon. Always collected as a pair with Umbreon, and slightly easier to find in high grade.",
    marketPrice: 286,
    change7d: 1.9,
    change30d: 6.6,
    weeklyVolume: 20,
    tags: ["neo", "eeveelution", "holo"],
    popScale: 2200,
  },
  {
    id: "c30",
    slug: "skyridge-crystal-umbreon-145",
    name: "Umbreon",
    pokemon: "Umbreon",
    pokedex: 197,
    setId: "skyridge",
    number: "145/144",
    rarity: "Secret Rare",
    type: "Darkness",
    hp: 80,
    illustrator: "Atsuko Nishida",
    year: 2003,
    releaseDate: "2003-05-12",
    description:
      "Crystal Umbreon. If the Evolving Skies alt art is the modern moon, this is the original glass one.",
    marketPrice: 6400,
    change7d: 0.7,
    change30d: 5.2,
    weeklyVolume: 2,
    featured: true,
    tags: ["crystal", "skyridge", "eeveelution", "grail"],
    popScale: 280,
  },
  {
    id: "c31",
    slug: "celebrations-mewtwo-10",
    name: "Mewtwo",
    pokemon: "Mewtwo",
    pokedex: 150,
    setId: "cele",
    number: "10/102",
    rarity: "Rare Holo",
    type: "Psychic",
    hp: 60,
    illustrator: "Ken Sugimori",
    year: 2021,
    releaseDate: "2021-10-08",
    description:
      "Classic Mewtwo, reprinted for the 25th. A cheaper way to own the pose without touching a 1999 sheet.",
    marketPrice: 18,
    change7d: -0.2,
    change30d: 1.4,
    weeklyVolume: 156,
    tags: ["reprint", "holo"],
    popScale: 19000,
  },
  {
    id: "c32",
    slug: "celebrations-mew-11",
    name: "Mew",
    pokemon: "Mew",
    pokedex: 151,
    setId: "cele",
    number: "11",
    rarity: "Promo",
    type: "Psychic",
    hp: 60,
    illustrator: "Yuu Nishida",
    year: 2021,
    releaseDate: "2021-10-08",
    description:
      "The Celebrations Mew with the floating silhouette. Common in boxes, uncommon in true gem slabs.",
    marketPrice: 24,
    change7d: 1.1,
    change30d: 3.6,
    weeklyVolume: 142,
    tags: ["reprint", "mew"],
    popScale: 16000,
  },
  {
    id: "c33",
    slug: "hidden-fates-pikachu-sv8",
    name: "Pikachu",
    pokemon: "Pikachu",
    pokedex: 25,
    setId: "hf",
    number: "SV8/SV94",
    rarity: "Secret Rare",
    type: "Lightning",
    hp: 70,
    illustrator: "Saya Tsuruta",
    year: 2019,
    releaseDate: "2019-08-23",
    description:
      "Shiny Vault Pikachu. Smaller money than the Charizard, cleaner joy, and a card that still moves at shows.",
    marketPrice: 48,
    change7d: 2.8,
    change30d: 7.4,
    weeklyVolume: 90,
    tags: ["shiny", "pikachu", "secret"],
    popScale: 12000,
  },
  {
    id: "c34",
    slug: "brilliant-stars-arceus-v-166",
    name: "Arceus V",
    pokemon: "Arceus",
    pokedex: 493,
    setId: "bs",
    number: "166/172",
    rarity: "Ultra Rare",
    type: "Colorless",
    hp: 220,
    illustrator: "Akira Komayama",
    year: 2022,
    releaseDate: "2022-02-25",
    description:
      "Trainer Gallery Arceus, painted like a stained-glass window. The grown-up chase from Brilliant Stars.",
    marketPrice: 36,
    change7d: 0.3,
    change30d: 2.1,
    weeklyVolume: 71,
    tags: ["gallery", "legendary"],
    popScale: 8900,
  },
  {
    id: "c35",
    slug: "paldea-iono-269",
    name: "Iono",
    pokemon: "Iono",
    pokedex: 0,
    setId: "pe",
    number: "269/193",
    rarity: "Special Illustration Rare",
    type: "Lightning",
    hp: undefined,
    illustrator: "kirisAki",
    year: 2023,
    releaseDate: "2023-06-09",
    description:
      "The streamer supporter that became a market of its own. Special illustration, pink hair, serious money.",
    marketPrice: 86,
    change7d: -1.4,
    change30d: 4.9,
    weeklyVolume: 103,
    tags: ["trainer", "sir", "paldea"],
    popScale: 7200,
  },
  {
    id: "c36",
    slug: "twilight-ogerpon-mask-210",
    name: "Ogerpon",
    pokemon: "Ogerpon",
    pokedex: 1017,
    setId: "tm",
    number: "210/167",
    rarity: "Illustration Rare",
    type: "Grass",
    hp: 110,
    illustrator: "Kouki Saitou",
    year: 2024,
    releaseDate: "2024-05-24",
    description:
      "The masked ogre of Kitakami, illustrated like a woodblock. Twilight’s most complete piece of folklore.",
    marketPrice: 28,
    change7d: 5.6,
    change30d: 12.1,
    weeklyVolume: 64,
    isNew: true,
    tags: ["illustration", "ogerpon"],
    popScale: 5100,
  },
  {
    id: "c37",
    slug: "base-set-zapdos-16",
    name: "Zapdos",
    pokemon: "Zapdos",
    pokedex: 145,
    setId: "base",
    number: "16/102",
    rarity: "Rare Holo",
    type: "Lightning",
    hp: 90,
    illustrator: "Ken Sugimori",
    year: 1999,
    releaseDate: "1999-01-09",
    description:
      "The electric bird. Unlimited holos are plentiful; the 1st Edition shadowless bird is a different conversation.",
    marketPrice: 176,
    change7d: 1.0,
    change30d: 3.5,
    weeklyVolume: 22,
    tags: ["vintage", "legendary", "holo"],
    popScale: 3200,
  },
  {
    id: "c38",
    slug: "base-set-raichu-14",
    name: "Raichu",
    pokemon: "Raichu",
    pokedex: 26,
    setId: "base",
    number: "14/102",
    rarity: "Rare Holo",
    type: "Lightning",
    hp: 80,
    illustrator: "Ken Sugimori",
    year: 1999,
    releaseDate: "1999-01-09",
    description:
      "Sugimori Raichu, mid-spark. A Base Set holo that still gets overlooked until a PSA 10 shows up.",
    marketPrice: 148,
    change7d: 0.5,
    change30d: 2.6,
    weeklyVolume: 18,
    tags: ["vintage", "holo", "pikachu-line"],
    popScale: 3000,
  },
  {
    id: "c39",
    slug: "neo-genesis-tyranitar-12",
    name: "Tyranitar",
    pokemon: "Tyranitar",
    pokedex: 248,
    setId: "neo-gen",
    number: "12/111",
    rarity: "Rare Holo",
    type: "Darkness",
    hp: 100,
    illustrator: "Shin-ichi Yoshida",
    year: 2000,
    releaseDate: "2000-12-16",
    description:
      "Johto’s tank. A Neo Genesis holo with better play history than most, which is why raw near-mints still feel tight.",
    marketPrice: 124,
    change7d: 2.1,
    change30d: 5.4,
    weeklyVolume: 15,
    tags: ["neo", "holo", "dark"],
    popScale: 1800,
  },
  {
    id: "c40",
    slug: "rocket-dark-dragonite-5",
    name: "Dark Dragonite",
    pokemon: "Dragonite",
    pokedex: 149,
    setId: "rocket",
    number: "5/82",
    rarity: "Rare Holo",
    type: "Colorless",
    hp: 70,
    illustrator: "Mitsuhiro Arita",
    year: 2000,
    releaseDate: "2000-04-24",
    description:
      "Arita’s Dark Dragonite. One of the few Rocket holos that can hang on a wall without looking like a novelty.",
    marketPrice: 274,
    change7d: 3.6,
    change30d: 8.2,
    weeklyVolume: 11,
    tags: ["rocket", "dark", "holo"],
    popScale: 1500,
  },
  {
    id: "c41",
    slug: "evolving-skies-umbreon-v-189",
    name: "Umbreon V",
    pokemon: "Umbreon",
    pokedex: 197,
    setId: "es",
    number: "189/203",
    rarity: "Ultra Rare",
    type: "Darkness",
    hp: 200,
    illustrator: "Teeziro",
    year: 2021,
    releaseDate: "2021-08-27",
    description:
      "The V before the VMAX. Same artist family, smaller canvas, still the card people buy when the alt art is out of reach.",
    marketPrice: 86,
    change7d: -0.8,
    change30d: 3.7,
    weeklyVolume: 69,
    tags: ["umbreon", "alt art", "v"],
    popScale: 9900,
  },
  {
    id: "c42",
    slug: "prismatic-leafeon-ex-155",
    name: "Leafeon ex",
    pokemon: "Leafeon",
    pokedex: 470,
    setId: "prism",
    number: "155/131",
    rarity: "Special Illustration Rare",
    type: "Grass",
    hp: 270,
    illustrator: "DOM",
    year: 2025,
    releaseDate: "2025-01-17",
    description:
      "Moss-light Leafeon from Prismatic. The quietest of the SIR Eeveelutions and the one most likely to be underpriced in six months.",
    marketPrice: 54,
    change7d: -4.1,
    change30d: -9.6,
    weeklyVolume: 58,
    isNew: true,
    tags: ["prismatic", "eeveelution", "sir", "new"],
    popScale: 2400,
  },
  {
    id: "c43",
    slug: "fossil-muk-13",
    name: "Muk",
    pokemon: "Muk",
    pokedex: 89,
    setId: "fossil",
    number: "13/62",
    rarity: "Rare Holo",
    type: "Grass",
    hp: 70,
    illustrator: "Mitsuhiro Arita",
    year: 1999,
    releaseDate: "1999-10-10",
    description:
      "Arita Muk. A sludge holo that vintage weirdos fight over and everyone else walks past — until the population report.",
    marketPrice: 88,
    change7d: 4.8,
    change30d: 11.3,
    weeklyVolume: 9,
    tags: ["fossil", "holo", "arita"],
    popScale: 2100,
  },
  {
    id: "c44",
    slug: "base-set-ninetales-12",
    name: "Ninetales",
    pokemon: "Ninetales",
    pokedex: 38,
    setId: "base",
    number: "12/102",
    rarity: "Rare Holo",
    type: "Fire",
    hp: 80,
    illustrator: "Ken Sugimori",
    year: 1999,
    releaseDate: "1999-01-09",
    description:
      "Nine tails, one holo stamp. A Base Set fire card that still looks expensive in a binder even when it isn’t.",
    marketPrice: 118,
    change7d: 0.2,
    change30d: 2.4,
    weeklyVolume: 16,
    tags: ["vintage", "holo", "fire"],
    popScale: 3100,
  },
  {
    id: "c45",
    slug: "shining-fates-eldegoss-sv011",
    name: "Eldegoss",
    pokemon: "Eldegoss",
    pokedex: 830,
    setId: "sf",
    number: "SV011/SV122",
    rarity: "Secret Rare",
    type: "Grass",
    hp: 90,
    illustrator: "Kouki Saitou",
    year: 2021,
    releaseDate: "2021-03-19",
    description:
      "A baby shiny that collectors bought as a palette cleanser and then refused to sell. Soft foil, small edition energy.",
    marketPrice: 22,
    change7d: 3.3,
    change30d: 8.1,
    weeklyVolume: 44,
    tags: ["shiny", "baby", "secret"],
    popScale: 6700,
  },
  {
    id: "c46",
    slug: "promo-mewtwo-12",
    name: "Mewtwo",
    pokemon: "Mewtwo",
    pokedex: 150,
    setId: "promo",
    number: "12",
    rarity: "Promo",
    type: "Psychic",
    hp: 70,
    illustrator: "Kagemaru Himeno",
    year: 2000,
    releaseDate: "2000-07-18",
    description:
      "The movie-era Mewtwo promo. Different posture than the Base Set holo, and a card that still shows up in attic collections.",
    marketPrice: 72,
    change7d: 1.7,
    change30d: 4.9,
    weeklyVolume: 31,
    tags: ["promo", "movie", "mewtwo"],
    popScale: 5400,
  },
  {
    id: "c47",
    slug: "twilight-bloodmoon-ursaluna-216",
    name: "Bloodmoon Ursaluna ex",
    pokemon: "Ursaluna",
    pokedex: 901,
    setId: "tm",
    number: "216/167",
    rarity: "Special Illustration Rare",
    type: "Colorless",
    hp: 260,
    illustrator: "OKACHEKE",
    year: 2024,
    releaseDate: "2024-05-24",
    description:
      "A red moon over Kitakami. The heaviest illustration in Twilight Masquerade, and the one that still climbs on quiet weeks.",
    marketPrice: 58,
    change7d: 7.2,
    change30d: 16.8,
    weeklyVolume: 49,
    isNew: true,
    trending: true,
    tags: ["twilight", "sir", "ursaluna"],
    popScale: 3900,
  },
  {
    id: "c48",
    slug: "brilliant-stars-charizard-v-154",
    name: "Charizard V",
    pokemon: "Charizard",
    pokedex: 6,
    setId: "bs",
    number: "154/172",
    rarity: "Ultra Rare",
    type: "Fire",
    hp: 220,
    illustrator: "Ryota Murayama",
    year: 2022,
    releaseDate: "2022-02-25",
    description:
      "Trainer Gallery Charizard V — the campfire portrait. Less foil than the gold VSTAR, more story.",
    marketPrice: 44,
    change7d: 1.9,
    change30d: 5.5,
    weeklyVolume: 88,
    tags: ["gallery", "charizard"],
    popScale: 10200,
  },
];

export const cards: Card[] = drafts.map((draft) => {
  const { popScale, ...rest } = draft;
  return {
    ...rest,
    priceHistory: history(draft.marketPrice, draft.id),
    recentSales: sales(draft.marketPrice, draft.id),
    listings: listingsFor(draft.id, draft.marketPrice, S),
    populations: pops(draft.id, popScale),
  };
});

export function getCard(slug: string) {
  return cards.find((card) => card.slug === slug);
}

export function getSet(slug: string) {
  return sets.find((set) => set.slug === slug);
}

export function getSetById(id: string) {
  return sets.find((set) => set.id === id);
}

export function getSeller(id: string) {
  return sellers.find((seller) => seller.id === id);
}

export function getListing(listingId: string) {
  for (const card of cards) {
    const listing = card.listings.find((item) => item.id === listingId);
    if (listing) return { listing, card };
  }
  return undefined;
}

export function cardsInSet(setId: string) {
  return cards.filter((card) => card.setId === setId);
}

export function relatedCards(card: Card, limit = 4) {
  return cards
    .filter((other) => other.id !== card.id)
    .map((other) => {
      let score = 0;
      if (other.pokemon === card.pokemon) score += 6;
      if (other.setId === card.setId) score += 3;
      if (other.type === card.type) score += 1;
      if (other.rarity === card.rarity) score += 1;
      return { other, score };
    })
    .sort((a, b) => b.score - a.score || b.other.marketPrice - a.other.marketPrice)
    .slice(0, limit)
    .map((entry) => entry.other);
}

export function featuredCards() {
  return cards.filter((card) => card.featured);
}

export function trendingCards() {
  return [...cards]
    .filter((card) => card.trending)
    .sort((a, b) => Math.abs(b.change7d) - Math.abs(a.change7d));
}

export function newCards() {
  return cards.filter((card) => card.isNew);
}

export function recentMarketSales() {
  return cards
    .flatMap((card) =>
      card.recentSales.slice(0, 2).map((sale) => ({ card, sale })),
    )
    .sort((a, b) => b.sale.date.localeCompare(a.sale.date))
    .slice(0, 18);
}

export const typeColors: Record<string, { ink: string; paper: string; foil: string }> = {
  Fire: { ink: "#7a1d12", paper: "#f3d2c4", foil: "#e85d04" },
  Water: { ink: "#16324f", paper: "#c9dcea", foil: "#2a6f97" },
  Grass: { ink: "#1d3b24", paper: "#d5e4c7", foil: "#4f772d" },
  Lightning: { ink: "#5c4300", paper: "#f3e3a3", foil: "#e9b10d" },
  Psychic: { ink: "#4a2156", paper: "#e6d0e8", foil: "#9b5de5" },
  Fighting: { ink: "#5a2a12", paper: "#ecd3c0", foil: "#b08968" },
  Darkness: { ink: "#1b1a28", paper: "#d4d0dc", foil: "#5c4d7a" },
  Metal: { ink: "#2b3038", paper: "#d5d8de", foil: "#8d99ae" },
  Dragon: { ink: "#3b2a12", paper: "#e6d7b0", foil: "#c9a227" },
  Fairy: { ink: "#6b2a44", paper: "#f0d0dc", foil: "#d47a9c" },
  Colorless: { ink: "#2f2a24", paper: "#e4ddd2", foil: "#8a8178" },
};
